# Form implementation generated from reading ui file 'c:\Users\Emily\Documents\GitHub\dndreader\evilmethod.ui'
#
# Created by: PyQt6 UI code generator 6.1.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EvilMethod(object):
    def setupUi(self, EvilMethod):
        EvilMethod.setObjectName("EvilMethod")
        EvilMethod.resize(400, 300)

        self.retranslateUi(EvilMethod)
        QtCore.QMetaObject.connectSlotsByName(EvilMethod)

    def retranslateUi(self, EvilMethod):
        _translate = QtCore.QCoreApplication.translate
        EvilMethod.setWindowTitle(_translate("EvilMethod", "Form"))
